apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaConnector"
metadata:
  name: "pdpa-oracle-connector-dev"
  labels:
    strimzi.io/cluster: thdlcd01-dev-connect-cluster
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.hostname: 
    database.port: ""
    database.user: ""
    database.password: ""
    database.server.id: ""
    database.server.name: ""
    database.dbname: ""
    database.whitelist: ""
    database.history.kafka.bootstrap.servers: thdlcd01-dev-kafka2-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: "kafka-tss-dev.pdpa-oracle"
    table.include.list: "STAGING.consent_tcustomerlist,STAGING.consent_tcustomerbasic,STAGING.consent_tdeliver,STAGING.consent_tdeliverresult,STAGING.consent_tconsentvalue,STAGING.consent_tconsentdoc,STAGING.tconsentfromsrcsys,STAGING.tconsenttosrcsys,ADAM_ODS.adam_consent_customer,ADAM_ODS.adam_consent_customer_basic,ADAM_ODS.adam_consent_deliver,ADAM_ODS.adam_consent_deliver_result,ADAM_ODS.adam_consent_value,ADAM_ODS.adam_consent_doc,ADAM_ODS.adam_consent_customer_history,ADAM_ODS.adam_cons_custm_basic_history,ADAM_ODS.adam_consent_deliver_history,ADAM_ODS.adam_cons_delv_result_history,ADAM_ODS.adam_consent_value_history,ADAM_ODS.adam_consent_doc_history,ADAM_ODS.adam_party_key_map,ADAM_ODS.adam_consent_sync_log_history,ADAM_ODS.adam_cons_notificatin_history"
    snapshot.mode: "schema_only"
    include.schema.changes: "true"
    topic.creation.default.partitions: 3
    topic.creation.default.replication.factor: 3
