apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaConnector"
metadata:
  name: "pdpa-sqlserver-connector-dev"
  labels:
    strimzi.io/cluster: thdlcd01-dev-connect-cluster
spec:
  class: io.debezium.connector.sqlserver.SqlServerConnector
  tasksMax: 1
  config:
    database.hostname: 
    database.port: ""
    database.user: ""
    database.password: ""
    database.server.id: ""
    database.server.name: ""
    database.dbname: ""
    database.whitelist: ""
    database.history.kafka.bootstrap.servers: thdlcd01-dev-kafka2-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: "kafka-tss-dev.pdpa-sqlserver"
    table.include.list: "dbo.tcustomerlist,dbo.tcustomerbasic,dbo.tdeliver,dbo.tdeliverresult,dbo.tconsentvalue,dbo.tconsentdoc,dbo.tpartydedupe,dbo.tsynclog"
    snapshot.mode: "schema_only"
    include.schema.changes: "true"
    topic.creation.default.partitions: 3
    topic.creation.default.replication.factor: 3
