apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaConnector"
metadata:
  name: "pg-connector-dev"
  labels:
    strimzi.io/cluster: thdlcd01-dev-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: "thazedpgdb0003.database.windows.net"
    database.port: "5432"
    database.user: "staging"
    database.password: "password"
    database.server.name: "db_staging"
    database.dbname: "db_staging"
    table.include.list: "test"
    database.history.kafka.bootstrap.servers: thdlcd01-dev-kafka2-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: "kafka-tss-dev.pg"
    decimal.handling.mode: "string"
    snapshot.mode: "initial_only"
    topic.creation.default.partitions: 3
    topic.creation.default.replication.factor: 3
