apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
  namespace: kafka-dev
spec:
  replicas: 3
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  http:
    port: 8080
  template: 
    pod:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: dedicated
                    operator: In
                    values:
                      - kafka
              topologyKey: "kubernetes.io/hostname"
 

